"""add name and created_by_user_id to templates

Revision ID: 0dd7e51067a5
Revises: a1b2c3d4e5f6
Create Date: 2026-01-02 17:51:45.238228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dd7e51067a5"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column("templates", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column(
        "templates", sa.Column("created_by_user_id", sa.String(), nullable=True)
    )

    # Update existing records with default values
    # Use a connection to execute raw SQL
    conn = op.get_bind()

    # Set default name for existing templates
    conn.execute(
        sa.text("UPDATE templates SET name = 'Untitled Template' WHERE name IS NULL")
    )

    # For created_by_user_id, we need to either:
    # 1. Delete existing templates (if they're all test data)
    # 2. Assign them to a specific user (if you have one)
    # For now, let's get the first user and assign existing templates to them
    result = conn.execute(sa.text("SELECT cognito_user_id FROM users LIMIT 1"))
    first_user = result.fetchone()

    if first_user:
        conn.execute(
            sa.text(
                f"UPDATE templates SET created_by_user_id = '{first_user[0]}' WHERE created_by_user_id IS NULL"
            )
        )
    else:
        # If no users exist, delete all templates
        conn.execute(sa.text("DELETE FROM templates WHERE created_by_user_id IS NULL"))

    # Now make columns non-nullable
    op.alter_column("templates", "name", nullable=False)
    op.alter_column("templates", "created_by_user_id", nullable=False)

    op.create_index(
        op.f("ix_templates_created_by_user_id"),
        "templates",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.create_unique_constraint(None, "templates", ["id"])
    op.create_foreign_key(
        None, "templates", "users", ["created_by_user_id"], ["cognito_user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.drop_constraint(None, "templates", type_="unique")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_index(op.f("ix_templates_created_by_user_id"), table_name="templates")
    op.drop_column("templates", "created_by_user_id")
    op.drop_column("templates", "name")
    # ### end Alembic commands ###
