"""remove_template_fk_from_documents

Revision ID: 65e39f5986b8
Revises: ae1f2046480b
Create Date: 2026-03-05 15:49:09.995446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65e39f5986b8"
down_revision: Union[str, Sequence[str], None] = "ae1f2046480b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    op.drop_constraint("documents_template_id_fkey", "documents", type_="foreignkey")
    # Then alter the column type from UUID to String
    op.alter_column(
        "documents",
        "template_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First alter the column type back to UUID
    op.alter_column(
        "documents",
        "template_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # Then recreate the foreign key constraint
    op.create_foreign_key(
        "documents_template_id_fkey", "documents", "templates", ["template_id"], ["id"]
    )
    # ### end Alembic commands ###
