"""create_documents_table

Revision ID: ae1f2046480b
Revises: 8639cbf34748
Create Date: 2026-03-05 15:10:42.901178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1f2046480b'
down_revision: Union[str, Sequence[str], None] = '8639cbf34748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.cognito_user_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_by_user_id'), 'documents', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_documents_template_id'), 'documents', ['template_id'], unique=False)
    op.create_index(op.f('ix_documents_token'), 'documents', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_token'), table_name='documents')
    op.drop_index(op.f('ix_documents_template_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expires_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by_user_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
